### ISSUE TITLE
Conditional exports and react native

### ISSUE THREAD

**Issue by SimonAM** [samhh/fp-ts-std#112]
15% of mobile apps are built using react native. And react in general seems to inspire people to delve deeper into functional programming.

However, react native doesn't like the way fp-ts-std implements conditional exports. 
If i can decipher the expo teams response on [this issue](https://github.com/expo/expo/issues/16130), its due to the use of regex expressions in fp-ts-std. 

Can someone explain what is the thing that creates the incompatibility and what would need to be changed in fp-ts-std?

**Comment by samhh** [comment]
On conditional exports you can usually patch in support in unsupported environments, per their example and with [Jest](https://github.com/samhh/fp-ts-std/issues/89). This is an Expo issue.

Regarding their mention of unicode property escapes, I think they're referencing the implementation of for example [isAlpha](https://github.com/samhh/fp-ts-std/blob/0689d4443db8b4df132c405f89465c9974ba3439/src/String.ts#L542) (the `\p{Alpha}` bit). This is an ES2018 feature that supposedly the [React Native JS runtime](https://reactnative.dev/docs/javascript-environment) doesn't support yet. All modern web browsers and [Node >=10](https://node.green/#ES2018-features--RegExp-Unicode-Property-Escapes) support it, including Safari which I believe uses the same underlying JS engine. As for why React Native/Expo doesn't seem to support it yet I can't offer any further insight, it's not an ecosystem I'm familiar with.
