### ISSUE TITLE
Record.mergeWith (using Ord)

### ISSUE THREAD

**Issue by anthonyjoeseph** [samhh/fp-ts-std#114]
Adapts [lodash's mergeWith](https://lodash.com/docs/4.17.15#mergeWith) using fp-ts idioms & type safety

```ts
import * as S from "fp-ts/string";

const test = mergeWith(
  { a: { b: 'hello' } },
  { a: { b: ' world', c: 123 }, e: false },
  { a: { b: S.Semigroup } }
)
/* test = {
  a: {
      b: "hello world",
      c: 123
  },
  e: false
} */ 
```

[runnable implementation (playground)](https://www.typescriptlang.org/play?exactOptionalPropertyTypes=true#code/PQ1hQIAQC4KYGcZRJM7zgMYHsB2SUCcAtgJYDmATjgK4AOAyjFWXhQFxSOmU0MAeJK3YA+KAF4oAbyi48WAIYwuACkUAaKACMAlJPEADACTTFAX1PbzhqOczzC8QlJJwqFOAHUyMABaq4FDBMlCKXLLaXADkfnAANvE40XZ2GkEhsuGhUVApAO44VPEAJtFaWFwAjABMAMxpUHBcAGaK8cRpGcHS3SHB2b39wyG5xOTUdEwsbBR9-fYL4LqQAFSwiMhSQyGD86NcAERxiThQhcUlh+kjwZVQtXV95jchzVBtHXDg5lCrwFBsPgEDh4nAAHRJCiqABSjAA8gA5cHCWZkFoAT1UzhguhWmHQhKJqGgZBI9DBbjwMGUZHwKGAaGJzMZ4DY8CobSwcG4vEmggAguIdnd8EoVFB1FwBVpcgL9BJxAKfpgYBj6DyACJwOD0ACy7k8AhlUAAQuIpAKmgAPeB4EoIKAAJTguCoJQEeFoJG07igAB8iDN2FpFHgMeIAPxmm12h3O11FD1en1+wOokNhcNRmR9ADaAGkoGwoABrOAYnAtKBWwPlyvV00AXS4Rbgtrg9sdqnrVZrUAAZGWK33Tfp9sFo9rdQaPHBjYWm1pTYvRBOoK3Y53473q1b19GBYv15v23HHbuzQezcfbhuoHg4AA3dw-e+1mPSgNX8BqjW8iZ+HoBBjWXC1+zPbdHRdN1k29X0qG-DMKFDbMoGjU0ty7BNYM9eC0yDEQUKzCN0NzfpC2LPBhwbfsh0vZsuB4QCphAo8CyXG8OLXX4mL5IDjW-c172YvgpkEwNzUwFpaAUGA6WosgEBgpNJWyWTSzwHB8jwfRZCoOAYFoKhqL-OA+0USQJCkaIcG0AArV0YBSAchwAQgFKgqEUDFwSUzzvKxRR9HscAZLkhSoDcOcfH8KBQLNURAn6bIZT6XJTVeYJxjEhgED4li8oSqTdC4ad9UNecTWEkVi2rVQ3KUlT3XUPFyNuAyjJMnQwkdcrZyNaq1yWfp0UlRrlMTFq9D09dOuM6jLMUPqdQqudiuGkJFhCRxkE6rhmrg1NEPTYNiLDUjtm20UCGQJQkCtKQlugqajoQpCztQiM+l2uRlpgTCpG0XqcKTPDjo+oivs2m7CHumBRP5ehJCIfjWJBw7wfe06oYA3L6AEC7RBhuRgWQesEEeqB4QcpzwQp1qfrJmiEEB6naawGB6YrBBVD0JnbpZ00cDiqQKYFcEWjIeIOR7Awhb8hR4loEpEB7PEBcICmYVoB6UfFyXpdl0t5bcinhf8RWsGV1XedLDX+l+7XdYB-WedNQ2ZfcOXFSgM33ZFvwrZttX7ZWfoWiKVQnYrKA+2dh7ZrvTq83rJsUfho80+ePpI6oaPmfrOPqwTgGk46wzU4rdOpHhlds6WXOo5jjFi6FwPy5GX7FAFLY-oequMSbddfu0XuM-++vq5H5mcqR8fa-+xGgMH4e7zGhqmte9Re-0Vy-a32C+d3zu7ygFO05RuegN78F5HFaP-qz6uKkn1fw9uX4Ek6Wrk8ry-XCVVigETOq9X5ICnkPLQ18pi73XNdOwfR5rdU6iDfqlUNo-CAA)

maybe a good candidate for a 'Struct' module, as per https://github.com/samhh/fp-ts-std/issues/110?

**Comment by samhh** [comment]
Deeply merging makes me nervous knowing TypeScript.

I wonder if there might be value in a `PartialSemigroup` typeclass. It'd be bridging the same gap but potentially in a more general way. The desired function would be provided by `concat` itself.

If `Semigroup` is a binary operation on `A`, `PartialSemigroup` would need to operate over an `A` and a `Partial<A>`? You lose deep merging.

Though that then makes me question why `A` isn't using `Option`s at which point it could just use `Semigroup`. :wink:
