### ISSUE TITLE
Re-exporting a sub-module

### ISSUE THREAD

**Issue by incetarik** [samhh/fp-ts-std#119]
Hello,
I was trying to have my utility functions along with the library function, so I have created a barrel file (`index` ) to export everything from the files I had and a sub-module of this library, like `Record`.

When I use TypeScript, there is no type error but I cannot get it work if I have the following setup:
```ts
// index.ts file in utility functions folder for Record structures

export * from './some-func-file'
export * from './another-func-file'

// The following does not have any type error
// but does not work when it is compiled
export * from 'fp-ts-std/Record'
```

**Comment by samhh** [comment]
We use this exact same pattern at work without issue. What bundler/environment are you using?

**Comment by incetarik** [comment]
> We use this exact same pattern at work without issue. What bundler/environment are you using?

I get this error when I want to use these with Jest (`ts-jest` more accurately).
I'll provide you my configurations now maybe that helps.

`tsconfig.json`

```json
{
  "compilerOptions": {
    "module": "commonjs",
    "declaration": true,
    "removeComments": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "allowSyntheticDefaultImports": true,
    "target": "es2017",
    "sourceMap": true,
    "incremental": true,
    "skipLibCheck": true,
    "noImplicitOverride": true,
    "rootDir": "./",
    "outDir": "./dist",
    "noImplicitAny": false,
    "strictBindCallApply": false,
    "forceConsistentCasingInFileNames": false,
    "noFallthroughCasesInSwitch": false,
    "strict": true,
    "declarationMap": true,
    "moduleResolution": "node",
    "typeRoots": [
      "node_modules/@types",
      "../@types"
    ],
    "paths": {
      "@core": [
        "."
      ],
      "@core/*": [
        "./*"
      ]
    }
  },
  "exclude": [
    "node_modules",
    "dist"
  ]
}
```

------

`package.json`, `"jest"` section:
```json
"jest": {
    "testEnvironment": "node",
    "setupFilesAfterEnv": [
      "@relmify/jest-fp-ts",
      "jest-extended/all"
    ],
    "moduleFileExtensions": [
      "js",
      "ts",
      "json"
    ],
    "moduleNameMapper": {
      "^@core(.*)": "<rootDir>/..$1"
    },
    "moduleDirectories": [
      "node_modules",
      "<rootDir>"
    ],
    "rootDir": "test",
    "testRegex": ".*\\.test\\.ts$",
    "transform": {
      "^.+\\.(t|j)s$": "ts-jest"
    },
    "collectCoverageFrom": [
      "**/*.(t|j)s"
    ],
    "coverageDirectory": "../coverage"
  }
```

So I have this configuration and with these, when I try to re-export from the `record/index.ts` file, along with my additional utility functions, that `export` is not usable in this way, of course it should work as also there is no type error but I would like to know your ideas about this as well.

This information might be useful: 
- My project is consisting of two sub-projects, so one is referencing the other (the `@core` path mapping is because of this).
- My `jest` tests are located in `test` folder as you can also see in the configuration,

**Comment by samhh** [comment]
Is this the issue perhaps?: https://github.com/samhh/fp-ts-std/issues/89

**Comment by incetarik** [comment]
> #89

Seems so yeah
