### ISSUE TITLE
`omit` should validate keys

### ISSUE THREAD

**Issue by OliverJAsh** [samhh/fp-ts-std#141]
```ts
declare const myProps: { foo: string; bar: string }
// error as expected ✅
pipe(myProps, S.omit(['egrravds']))
// no error?? ❌
pipe(myProps, S.omit(['foo', 'egrravds']))
```

Related change: https://github.com/samhh/fp-ts-std/commit/a4a95eb1

Why would you try to omit a key that doesn't exist on the type? Do you have an example of when you would want to do this? I looked at the test [in this commit](https://github.com/samhh/fp-ts-std/commit/a4a95eb1) but I'm not sure it provides a realistic example.

**Comment by samhh** [comment]
This was the intention I think, but it doesn't actually seem to work:

```ts
type Foo = { foo: string; extra1: string }
type Bar = { bar: string; extra2: string }

const f = omit(["foo", "bar"]) // supposed to be usable on both Foo & Bar

pipe({} as Foo, f)
```

Tempted to just revert that commit for 0.15.

**Comment by OliverJAsh** [comment]
You could probably make that word by reading all keys in the union: https://www.typescriptlang.org/play?ssl=1&ssc=1&pln=2&pc=1#code/C4TwDgpgBAggNnA0hEBnAPAFQHxQLxSZQQAewEAdgCapQCGFIUA-FANYoD2AZoVAFxQKEAG4QATgChQkKACV8sBMjToA3lG6dOzQamDiAlhQDmUAL5QAPlA0AjOuN1R9R0xeySA9F6h+AesxAA

**Comment by samhh** [comment]
https://github.com/samhh/fp-ts-std/commit/b3d8ab0e527780a1da0516668488306c13982231
