### ISSUE TITLE
`Record.pick` & `Record.omit`

### ISSUE THREAD

**Issue by samhh** [samhh/fp-ts-std#143]
`Struct.omit` [now behaves more sensibly](https://github.com/samhh/fp-ts-std/issues/141), however this leaves a space where a `Record.omit` should be. `Record.pick` should possibly be included too for symmetry?

```hs
omit :: Array string -> Record string a -> Record string a
```

```ts
export const omit = (xs: Array<string>): (<A>(y: Record<string, A>) => Record<string, A>) =>
  R.filterWithIndex(A.elemV(Str.Eq)(xs));
```

**Comment by milespossing-msft** [comment]
Is there any reason no one has done this? I could probably find some time to toss such a change in this weekend

**Comment by samhh** [comment]
No reason, I've just had less energy in the last few months so my own open source contributions have been a bit slower. I'll review any PRs if you'd like to contribute. 🙂

**Comment by samhh** [comment]
https://github.com/samhh/fp-ts-std/commit/ebb3ecb39837c2320b32d0d58a98e4f2a6c062c4 & https://github.com/samhh/fp-ts-std/commit/759201d365ef4e9d217c171f256652e6c807d826

**Comment by milespossing-msft** [comment]
@samhh is a god among men
