### ISSUE TITLE
`is` testing with primitives

### ISSUE THREAD

**Issue by imcotton** [samhh/fp-ts-std#154]
In short, **Ramda** has such test cases down below which contrast with **fp-ts-std** currently:

> https://github.com/ramda/ramda/blob/v0.28.0/test/is.js#L57-L61
```js
it('recognizes primitives as their object equivalents', function() {
  eq(R.is(Boolean, false), true);
  eq(R.is(Number, 0), true);
  eq(R.is(String, ''), true);
});
```

Do you think it makes sense to align implementations between?

> https://github.com/ramda/ramda/blob/v0.28.0/source/is.js#L28-L33
```js
var is = _curry2(function is(Ctor, val) {
  return val instanceof Ctor ||
    val != null && (
      val.constructor === Ctor ||
      (Ctor.name === 'Object' && typeof val === 'object'));
});
```

v.s.

https://github.com/samhh/fp-ts-std/blob/1036583d03426e7793f38ce7cd5eebc1832d0764/src/Function.ts#L798-L804

**Comment by samhh** [comment]
Probably not.

Ramda wasn't written with static typing in mind. From my perspective `is` is primarily intended for testing against class instances, like subclasses of `Error`. Not a pattern I necessarily love but it comes up. If you want to compare primitive types or records/structs I'd recommend something like io-ts.

**Comment by imcotton** [comment]
Fair enough, will combine with **io-ts** as complement.

On the side note, I was migrating some legacy code from **Ramda** over `is`, luckily there was one indirect cache related test case caught the predicate difference.

I wondered docs could use some help, or renaming to something like `isInstance` to make it more obviously.

**Comment by samhh** [comment]
Is the current documentation unclear? I think it directly references `instanceof`.

**Comment by imcotton** [comment]
I mean since this `is` not mirror to Ramda functionality-wise, naming could also vary.

Code like `pipe( 'abcd', is (String) )` makes sense to me the most, it's hardly to justify otherwise.

**Comment by samhh** [comment]
That makes sense. It could improve readability to have a more explicit name. How about `isInstanceOf`? Looks like that'd match Scala.

**Comment by imcotton** [comment]
> How about `isInstanceOf`? Looks like that'd match Scala.

That is a perfect consensus 👍

**Comment by samhh** [comment]
Would you like to make a PR? No rush, and I can make the change if not. :slightly_smiling_face:

**Comment by imcotton** [comment]
I'd like to, on to making the PR now.

**Comment by imcotton** [comment]
I'd like to, on to making the PR now.

**Comment by samhh** [comment]
Thanks!
