### ISSUE TITLE
Feature Request: `minimumBy` and `maximumBy`

### ISSUE THREAD

**Issue by imcotton** [samhh/fp-ts-std#161]
Addition features next to `minimum` and `maximum`, something like:

```haskell
:: (a -> b) -> Ord b -> ReadonlyNonEmptyArray a -> a
```

**Comment by samhh** [comment]
Looks solvable with [`Ord.contramap`](https://gcanti.github.io/fp-ts/modules/Ord.ts.html#contramap)?

As an aside I believe the Haskell convention of a "by" suffix is where an `Ord` constraint is omitted and a predicate or comparison or what have you is supplied directly instead.

**Comment by imcotton** [comment]
Yes I was thinking about `contramap`, however to follow **Haskell**'s convention, do you think it's also necessary to provide

```haskell
comparing :: (a -> b) -> Ord b -> (a -> a -> Ordering)
```

as packed deal to compose with

```haskell
maximumBy :: (a -> a -> Ordering) -> ReadonlyNonEmptyArray a -> a
```

In this way it aligns to **Haskell**, but somehow skipped `contramap`? Or it's actually just be OK?

**Comment by imcotton** [comment]
You are right, on the second thought by having `maximum` alongside with `contramap` is sufficient enough to cover the usage, I was getting a blind angle between two systems, thanks for help to clarify.
