### ISSUE TITLE
Cannot be used in React Native project

### ISSUE THREAD

**Issue by liambutler-lawrence** [samhh/fp-ts-std#162]
We use `fp-ts` and `fp-ts-std` in a shared library consumed by both node.js and React Native projects. In the node.js project, both work perfectly, but in React Native, only `fp-ts` works, while importing `fp-ts-std` causes the app to crash at launch, saying it can't find the imported file.

Has anybody else seen this issue?

**Comment by samhh** [comment]
Your build tool and/or runtime environment need to support [conditional exports](https://nodejs.org/api/packages.html#conditional-exports).
