### ISSUE TITLE
fp-ts backports

### ISSUE THREAD

**Issue by samhh** [samhh/fp-ts-std#182]
Some stuff that can potentially be dropped here:

- [`tap`](https://github.com/gcanti/fp-ts/pull/1857)
- [`mapBoth`](https://github.com/gcanti/fp-ts/pull/1872)

Additionally some new aliases:

- `flatMap` for `chain`
- `mapError` for `mapLeft`

**Comment by stefanoCrmg** [comment]
https://github.com/samhh/fp-ts-std/pull/185 should partially solve this issue.
I did not remove any of the `mapBoth` as it was not released with `fp-ts@2.15.0`.

Is there any of function that you think would be a good fit for being made `dual`? https://github.com/gcanti/fp-ts/blob/master/src/function.ts#L773

Ideally I guess it would be great to have everything as `dual` but I'd say that maybe converting all of the `unsafeUnwrap` functions could be a good starting point?

**Comment by samhh** [comment]
I'm not personally interested in supporting data-first. It's not how I'd advise anyone to write functional code and it harms maintainability here. Open to other perspectives.
