### ISSUE TITLE
get for struct

### ISSUE THREAD

**Issue by forno** [samhh/fp-ts-std#183]
typesafe get for struct. 

```
  <K extends string | number | symbol>(path: K) =>
  <A>(obj: { [P in K]: A }): A
```

I would like to propose the addition of a get function to struct.

This get function would take a  key as input and return the value directly. It would first receive the struct type, then verify whether the prop exists. If the prop doesn't exist, a compile-time type error would be thrown.

This design is to ensure type safety when accessing elements of a struct, with errors being caught at compile time rather than at runtime.

**Comment by samhh** [comment]
Thanks! This could be a useful shorthand that's cheaper than lenses.

"Lookup" to me implies a record. Maybe `get`, or `_` (thinking of PureScript), could make more sense?:

```ts
const getX1 = S.get('X')
const getX2 = S._('X')
```

Probably `get` given the namespacing norm in fp-ts. WDYT?
