### ISSUE TITLE
`N.fromString()` should not use `Number.parseInt()`

### ISSUE THREAD

**Issue by imhoffd** [samhh/fp-ts-std#196]
Hello! Firstly, I want to say what a great library this is. It is the perfect companion to fp-ts. 

I noticed while reading the source code that [`N.fromString`](https://github.com/samhh/fp-ts-std/blob/666f3b0a02536930a1f95ce5f5865e1df1bfbd7f/src/Number.ts#L68-L69) uses `N.fromStringWithRadix(10)`, which ultimately uses the built-in `Number.parseInt`. I think this is a mistake, as JavaScript numbers are not necessarily integers, yet the documentation for the method states "Convert a string to a number."

Would you accept a PR that does the following?
- deprecates `fromString` and `floatFromString`
- creates the following methods:
  - `fromStringToInteger(s: string): Option<number>` -- uses fromStringWithRadix
  - `fromStringToFloat(s: string): Option<number>` -- does NOT use fromStringWithRadix, uses `Number.parseFloat`
  - `fromStringToNumber(s: string): Option<number>` -- does NOT use fromStringWithRadix, uses `Number` constructor

It is arguable that `N.fromStringWithRadix` should also not use `Number.parseInt`, as it's possible to have a decimal separator in numbers whose radix=10. Additionally, numbers with other base notation can also have a [radix point](https://en.wikipedia.org/wiki/Decimal_separator#Radix_point).

**Comment by samhh** [comment]
Hey, just wanted to say that I've been busy lately but I will get around to looking at your PR before fp-ts-std's next release, whenever that is. 🙂

**Comment by imhoffd** [comment]
No worries! We're all busy. Take your time, and thanks for the update!
