### ISSUE TITLE
Unable to import fp-ts-std

### ISSUE THREAD

**Issue by sahilsehwag** [samhh/fp-ts-std#198]
Error: `Cannot find module 'fp-ts-std/Function' or its corresponding type declarations.`

I have tried all the solutions mentioned in different comments across different issues relating to this. But I am unable to use fp-ts-std. I am using this library in a chrome extension I am building using react and webpack.

**Comment by sahilsehwag** [comment]
webpack: 4.44.2
typescript: ^5.0.2

**Comment by Mati365** [comment]
In my setup eslint is failing with the same error.

**Comment by samhh** [comment]
@Mati365 Is that eslint-plugin-import?: https://github.com/import-js/eslint-plugin-import/issues/1810

**Comment by Mati365** [comment]
@samhh yep
