### ISSUE TITLE
Task logDuration

### ISSUE THREAD

**Issue by steida** [samhh/fp-ts-std#20]
To log a task duration. Something like this. I suppose it can be useful.

```ts
export const logDuration = <A>(ma: Task<A>): Task<A> => {
  return () => {
    const start = Date.now();
    return ma().then((a) => {
      // eslint-disable-next-line no-console
      console.log(`${(Date.now() - start) / 1000}s`);
      return a;
    });
  };
};
```

**Comment by samhh** [comment]
Am I writing in thinking this'd be principally used for debugging?

**Comment by steida** [comment]
@samhh Yep.

**Comment by samhh** [comment]
How do you like the look of this?:

```typescript

export const elapsed = (f: (ms: number) => IO<void>) => <A>(x: Task<A>): Task<A> => async () => {
    const start = Date.now();
    const y = await x();
    const duration = Date.now() - start;
    // eslint-disable-next-line functional/no-expression-statement
    f(duration)();

    return y;
};
```

Then to achieve the same you could just `elapsed(log)` (where `log` comes from `fp-ts/Console` and is `unknown -> IO void`).

Only thing I'm unsure about is how idiomatic it is to use a callback for side effects.

**Comment by samhh** [comment]
https://github.com/samhh/fp-ts-std/commit/02c9e5b2574a12dcc7825498811b9dfdd1d1383e

Will be included in the next release, thanks for the suggestion! :slightly_smiling_face:
