### ISSUE TITLE
As compared to Ramda: equals - checkmark should probably be unchecked

### ISSUE THREAD

**Issue by extremegf** [samhh/fp-ts-std#200]
Doc says:
> equals - [fp-ts/Eq](https://gcanti.github.io/fp-ts/modules/Eq.ts.html)

However now relevant functions in fp-ts are deprecated. 
As far as I understand neither fp-ts nor fp-ts-std provides function equivalent to R.equals:

```ts
const equals3 = R.equals(3);
R.all(equals3)([3, 3, 3, 3]); //=> true
R.all(equals3)([3, 3, 1, 3]); //=> false
```

So `equals` should probably be changed to unchecked in the doc.

**Comment by samhh** [comment]
I'd argue this falls under:

> Note that some functions are not one-to-one replacements, but rather bequeath a better pattern in code.

Most types have `Eq` instances upstream which in turn can be used with combinators like `A.getEq` to achieve similar results without the magic. In this case you could substitute with:

```ts
const equals3: Predicate<number> = x => Num.Eq.equals(x, 3)
const all3: Predicate<Array<number>> = A.every(equals3)
```

The use of `Eq` over `===` here isn't strictly necessary however it expresses how much more powerful `Eq` is for more complex data types with more nuanced notions of equivalence.

**Comment by extremegf** [comment]
I guess thats ok.
