### ISSUE TITLE
Coverage incorrectly reported as <100%

### ISSUE THREAD

**Issue by samhh** [samhh/fp-ts-std#24]
On develop branch in CI. 100% locally with Node 15.

**Comment by waynevanson** [comment]
`fp-ts` has some stuff that contains `istanbul-ignore`, where istanbul is the code coverage tool used internally.

When I was writing tests for `fp-ts-rxjs`, I had the same issue. Unsure if `fp-ts` or `istanbul` is at fault, but it's something to consider.

**Comment by samhh** [comment]
So I fixed the initial issue by making the CI pipeline use Node 15 (as Jest is configured to use V8 to determine coverage, and that seems to have improved over time).

Now it's broken again with the new main/index module... no need for coverage there.

**Comment by samhh** [comment]
https://github.com/samhh/fp-ts-std/commit/215df73fa4aaa544b7f9e23dc13acfc9909de819
