### ISSUE TITLE
critical: packagejson does not contain field "main"

### ISSUE THREAD

**Issue by waynevanson** [samhh/fp-ts-std#26]
The files are included with the package but since `package.json` does not have field `main`, it doesn't know where to look.

**Comment by waynevanson** [comment]
It's apparent that there is no single entrypoint. I'd like to use the library using `import { string } from 'fp-ts-std'`

Would you be okay with this?

**Comment by samhh** [comment]
Definitely, let's make that happen in a 0.5.1 release.

**Comment by samhh** [comment]
This is now published under [0.5.1](https://github.com/samhh/fp-ts-std/blob/master/CHANGELOG.md#051-2020-10-30). :slightly_smiling_face:
