### ISSUE TITLE
Array Concat

### ISSUE THREAD

**Issue by tecklund** [samhh/fp-ts-std#40]
I'm a little tired of using a Monoid to concat arrays together all the time, how would y'all feel about a convenience function for Array like

`const concat = <A>(a:A[]) => (b:A[]) => A.getMonoid<A>().concat(a, b)`

just so we can pipe some stuff together like

`pipe(R.keys(x), concat(R.keys(y)), A.uniq(eqString))`

**Comment by samhh** [comment]
https://github.com/samhh/fp-ts-std/commit/f53870943634d942b406314d98eee31ab8ad4eff
