### ISSUE TITLE
zipAll proposal

### ISSUE THREAD

**Issue by tecklund** [samhh/fp-ts-std#41]
Zip currently only works for arrays of the same size, which is sometimes fine but sometimes you want to zip up uneven arrays and keep the parts that were uneven. How about a function like:

```
const zipWithAll = <A, B, C>(
  fa: ReadonlyArray<A>, 
  fb: ReadonlyArray<B>, 
  f: (a: O.Option<A>, b: O.Option<B>) => C): ReadonlyArray<C> => {
  const fc: Array<C> = []
  const len = Math.max(fa.length, fb.length)
  for (let i = 0; i < len; i++) {
    fc[i] = f(i < fa.length ? O.some(fa[i]) : O.none, i < fb.length ? O.some(fb[i]) : O.none)
  }
  return fc
}

// zip but just gives arrays of size 1 when its uneven
const zipAll = <A, B, C>(fa: ReadonlyArray<A>, fb: ReadonlyArray<B>) =>
  zipWithAll(fa, fb, (a, b) => A.compact<(A|B)>([a, b]))
```

```
zipAll([1,2,3], [4,5])
// => [[1,4], [2, 5], [3]]
```

**Comment by samhh** [comment]
One issue I have with this right now is that the return type becomes widened to accommodate for the different shape of the final item.

We could return something like this to keep them distinct: `[Array<[A, B]>, Array<A | B>]`

Or if we're willing to provide monoid instances we can ditch the union and match the return type of `zip` (`Array<[A, B]>`).

Thoughts?

**Comment by tecklund** [comment]
Hmm, it's a good point - A.compact does widen the type a bit. zipWithAll is general enough that I think you could go a bunch of ways with it - like if you wanted to keep the tuples you might do 

```
const zipAll = <A, B, C>(fa: ReadonlyArray<A>, fb: ReadonlyArray<B>): ([A, B] | [A] | [B])[] =>
    zipWithAll(fa, fb, (a, b) => 
    O.isSome(a) && O.isSome(b) ? [O1.unsafeUnwrap(a), O1.unsafeUnwrap(b)] :
    O.isSome(a) ? [O1.unsafeUnwrap(a)] :
    [O1.unsafeUnwrap(b)])
```

or we could keep the Option info itself like

```
const zipAll = <A, B>(fa: ReadonlyArray<A>, fb: ReadonlyArray<B>) : [O.Option<A>, O.Option<B>][] =>
    zipWithAll(fa, fb, (a, b) => [a,b])
```

I'm not sure though, it would depend on the use case. I can see how a user might want any of those depending on what they needed the function for. 

I'm not sure I follow about monoid instances, can you show me an example of what you mean?

**Comment by samhh** [comment]
The output of zipping here is generally `[A, B]` _except_ when there's an imbalance in the number of items, in which case you have a series of trailing `[A]` or `[B]`. If a monoid for each of `A` and `B` was provided then we could maintain the `[A, B]` return type.

So the question is: Is it plausible and useful to provide monoids instances? Or do we want to know which items were "dangling"?

**Comment by tecklund** [comment]
I think I see, do you mean provide an identity to balance out the array? I'd rather not lose info, we should be able to tell which ones are dangling. I'm ok with having a union type, it seems like the least bad option

**Comment by samhh** [comment]
Yeah that's what I was getting at.

Another idea per [here](https://stackoverflow.com/questions/41336345/does-haskell-have-a-greedy-zip-one-preserving-all-elements/41336753) would be to represent everything with `These`: `Array<These<A, B>>`

I'm feeling like that might be a happy middle ground between retaining information and ergonomics.

**Comment by tecklund** [comment]
Right on, yeah this would work 

```
const zipAll = <A, B>(fa: ReadonlyArray<A>, fb: ReadonlyArray<B>) : T.These<A, B>[]  =>
    zipWithAll(fa, fb, (a, b) => O1.unsafeUnwrap(T.fromOptions(a,b)))
```

**Comment by samhh** [comment]
https://github.com/samhh/fp-ts-std/commit/6dfad7c56f23cfc15f975ae8d21dff41fe6e2b04
