### ISSUE TITLE
parseInt proposal

### ISSUE THREAD

**Issue by anthonyjoeseph** [samhh/fp-ts-std#43]
Hello! I'm a big fan of this library!

Maybe it would be useful to have a `parseInt` function in `Number.ts`? It might help with https://github.com/samhh/fp-ts-std/issues/29

```ts
import {flow} from 'fp-ts/function'
import * as O from 'fp-ts/Option'
import {invert} from './Boolean'

const parseInt = flow(Number.parseInt, O.fromPredicate(invert(isNaN)))
```

Or is this too trivial to be worth it?

**Comment by samhh** [comment]
Hey, cheers! :slightly_smiling_face: 

That could be handy. I'd lean towards `fromString` for consistency with `fromNumber`'s naming in the `String` module.

```hs
fromString :: string -> Option number
```

Also as an aside you might find `isValid` handy in your snippet, replacing `invert(isNaN)`.

**Comment by anthonyjoeseph** [comment]
Oh ok that makes sense! And I love `isValid` - I hadn't noticed that. Would you consider a PR if I made one for `fromString` and `floatFromString`?

**Comment by samhh** [comment]
Absolutely! :+1:

**Comment by anthonyjoeseph** [comment]
Huh I wonder why this didn't auto-close.

Yay it's a feature now!
