### ISSUE TITLE
New implementations for `pick` and `omit`?

### ISSUE THREAD

**Issue by anthonyjoeseph** [samhh/fp-ts-std#46]
Here's a [rough draft of the concept](https://www.typescriptlang.org/play?#code/C4TwDgpgBAqgdgSwPZwCpIJJ2BATgZwgGNhk4AeVAPigF4oAoKKAClSggA8c4ATfKAEM4IKAH5WnAFxRUASjo1homXAgA3PAq49+TSTIRwAZnigAlBbSUjxFqKo14GDUJFkR8wADIIcuQQAbcgBpDm4IPgEvXCMAcxp6fRj48N0BMIkAVzgAazgkAHc4B0ZmZgBtEIBdNMj+KAr4MnQsf0ISMlCqWokwmRz8orgXN2gAUTh8LNwIX38g1CywQIhyAEE6qKgUuDiK6sSoQYLirYaAb30qiFEjKFzbpGModeqZdZuQWp166OBYns7KhPD4-HgghsvodSidhgwAL4VOBZAC2ACM8L0oGpNLhSusXEQUF4oGAEERcnQoKFbgJfttdvtDix9AA6Dm5fAySbTWbzCGBJYrNYhOlUBhWGgbc4CC6NR53EpikD4ZFozG4arvY55U4lBFUVnMaSvAA0kpk8qqUHuKrVKIxWJ1nxqUARiigV2YxKmwCgSGpFw9gjljTCdrp6qdWpdVVqCP0AHoAFQcfCBIzAAC0vAQ+EE6NWUBTSf0xiQ+JYvtJVOeDwEoag9ujmuqBwU3vKSAquVq9E4veq+kTzFT6cz2GzkULxdL+lmwBmJSQiKJJP9SFRfmptNVsp2APiByN7M53KgvJmc3BASFy1We-wEqlNM2DMuCtutuVUcdbZ1OEzkNY0TQ+C05CtcMf0vTgiECLJeDWRV63WM1mz-DUsR6D543dT0uxrTcgxDMMbXucY4IQpDyBQl40Iw1VW2wuM3VHKAKyrIiHgDF4AHl0QAK2IYA2UVfAWE4BQmxbf8sQ7L19GYBAXhYABCLk2SMeDEM8FhcjkTslPKFhAybZQ5CHalBz7Yz2PYxdlwDNcGBrJBVjZQIkDiFhyUpFgAHJBAC9CAvRAK5BYeVBBkABGdD0RkAAmdCiBkABmBFDNckl3IgTzvN8ilckC4KhAEIKAqgAAfKAAqIEK6vCyLorihLktSjKsoUJMkx-HhSBQIIOFwXBKxyqY8oKnytz8UrGrCiKoqENqoESqAUqgNKoEy7K3I8ryZu3YB5vKuqytq+qFua5aYqgeK1o6rausMqBev6yJBrgYa8DG3AGCAA). `Pick` has become a bit simpler, and they both now accept rest parameters. `Omit` (may?) have better performance characteristics w/o the use of `delete` (though this is unclear)

Not sure if one or neither of these are desired as they are breaking changes, but I can spin up a PR if it is/they are!

P.S. Credit to @qlonik for [UnionToIntersection](https://github.com/gcanti/fp-ts/issues/1460#issuecomment-811166087) and for the [delete](https://github.com/gcanti/fp-ts/issues/1460#issuecomment-812091015) research

**Comment by samhh** [comment]
In my mind I quite like the idea of declaring the type we intend to pick ahead of time but honestly I can't argue a good reason for it. :thinking: I commented in an fp-ts thread recently something equivalent to `pick` and `pickFrom` helpers, that might be useful.

One thing I'd really like to maintain is that it takes an array as input. For me, rest/spread makes functional code harder and doesn't ergonomically offer anything over arrays except dropping two characters. Is there a perfomrance or type-related reason to prefer rest params?

Don't worry about breaking changes for now, we're 0.x so provided they're good and well thought out changes it's all good and adhering to semver.

**Comment by anthonyjoeseph** [comment]
I can't find the comment in the  Is the idea to rename the current pick signature to `pickFrom`, and use the new one for `pick`?

**Comment by waynevanson** [comment]
I definitely wasn't expecting `pick` to be a function call. I would drop it personally. The type is ALWAYS unknown for the `A` type. We can at least give it a chance to infer if we remote the first function call.
