### ISSUE TITLE
`set` and `setW` in the `Record` module?

### ISSUE THREAD

**Issue by anthonyjoeseph** [samhh/fp-ts-std#47]
Port of lodash's [set](https://lodash.com/docs/4.17.15#set) - might be helpful for https://github.com/samhh/fp-ts-std/issues/29

[Implementation](https://www.typescriptlang.org/play?#code/C4TwDgpgBAqgdgSwPZwCpIJJ2BATgZwgGNhk4AeVAPigF4oAoKKAClSggA8c4ATfKAEM4IKAH5WnAFxRUASjo1homXAgA3PAq49+jZi2lQEcAGZ4oAJQW0lI8VaiqNeBg1CQoAUTj4ArrgQADIIOLiCADbkANIc3BB8AvjAuCYA5jT0TFDJqXBpcboCsRJqmrhO+lAA2tEAuoUJetXwZOhYYYQkZDFUDRKxzuVuAPQAVGNMY1AAyhDAAoJQANYQIADkAuqRftAmQjkpfiQAdFbzAb4HaQl4CERQAAY+vEgAtki4YAAWCPhvjym+mmAAEuII3mAIhAgQhIZ9gFBpoIBDMoKZcO8oOtTGAALQLPHJXgjSzET68daw+G4RHIgQAeXRmLe2NxBPwIwZYFIKCpSKBRBQyXRcBk5AAgo1ElAAN5CVR+N4AIwsAF8qCwkMqAFYyCU2GhS2zMegzE6EYAsdaCdYAGigACY5ECgSjCLSTrwIBAwDMUvdgF4AI5+SIsIHMMAISAseWCGQARgdypk62V6ygaodpjgcjtkblCqdKbTGazQJdSKE+A9wC9Pr9AZIIbDEQj1ajMYgceLyagqex5ezswt82ttodzvzUBGIyg5DxeKEfmASCFkOhOHRn2xtsL8ZkjtLQ8zasrUyBIKIghwaU+og3ypMt8++Cv+BMRGgAGYTgAGACphGBguDABEoCFXxEUtOgF2yaI1mlPQO2YFY1iQUwoClHQmgEMoLAkXJ0kqbI0PQkBMOw5CkgDfIHFWSisKlIZXGYfNsglAtmAANQYTVskYmQfH8QIQjCSIYjWKgHWybYIl2GRENEXCZUYqipQkCVajWBoZD4w14OYAAhGii2qZZjDgKBlLqfSKwE5htT1CiNLMgiKgkUz9QYOQZHU5j3JcTyoG86iTV7E4ouch0LN0mR5N2LMFBRIQRFGCYgTmBYDkYzYoESvZrKWXJjmAB0AHcEG9RB6OAb5oA8CATldaswU4CEoRhas4XA2lq1StEMSxHF8UJYlSXJXBKWpPq6RrKAmWG1lRo5LkeTIflpjdWs8Hrb1fX9VIW1DcNC2jWNDygftBxtM8HXNS0AHUJ3tPd1jkGc5wXJcVzXDcuu3Uxdzug9i3WAAvN7bttCtqyrSY2pvO8H0g95nzgV8CA-L9fwAoCkRAsCIKgkVnrg8gEKQ1SULI1zApp-DgocYj6JkOnmAC6jGcOPICgkLmWKgDzsg45guOyPjHIopTqfiGVWf57xfACYJQjwSTlJoWWQFk5hCv03zFCM0KzPlCyrJs+KoD8OBljgJAKus89NWc-yMIZ+W9A8hwwoNKQqZUr2BEF7IJHNgAFS3BbsqAo555SHG0iO9KgHi4cqSPo490LY-j4OrdELzqhTyp07VRRski6LdVixjY8K5KFuUBggA)

Credit to @qlonik for the idea and for `EnsureLiteral`

**Comment by samhh** [comment]
I like it! Would you mind opening a PR? My only requested change would be that it's fully curried. :slightly_smiling_face:

**Comment by anthonyjoeseph** [comment]
Yeah that's exactly right. It's purely an ergonomics issue.

I've attempted to solve this same ergonomics problem w/ my library [spectacles-ts](https://dev.to/anthonyjoeseph/simple-immutable-data-w-spectacles-4nb5), which has a `set` very much like the one proposed here (plus some additional functionality)

I'll close this here for now, since it exists elsewhere in the fp-ts ecosystem
