### ISSUE TITLE
DOM APIs

### ISSUE THREAD

**Issue by samhh** [samhh/fp-ts-std#5]
Probably out of scope if we want to support Node? Or perhaps not, Node users would just need to not import those. Or `fp-ts-dom`?

**Comment by waynevanson** [comment]
I'm working on something called dom-ts. It's precise in terms of how to construct signatures but still in development.

**Comment by samhh** [comment]
Awesome! I'll consider that out of scope then.

**Comment by waynevanson** [comment]
Fp-ts dom is a good name though!

There's basically a huge headache inferring event listeners from a tag name or element because typescript doesn't come with an indexable way to up the relationship between them.

That's why you may see the meta namesake being used.
