### ISSUE TITLE
Document fork as replacement for juxt in Ramda?

### ISSUE THREAD

**Issue by imcotton** [samhh/fp-ts-std#58]
ref:
- https://ramdajs.com/docs/#juxt
- https://samhh.github.io/fp-ts-std/modules/Function.ts.html#fork

**Comment by samhh** [comment]
Thanks for the reminder! That slipped my mind.

https://github.com/samhh/fp-ts-std/commit/d3d6440f6bd77986b721270b736ef20fb24d40dc
