### ISSUE TITLE
Re-exporting fp-ts

### ISSUE THREAD

**Issue by samhh** [samhh/fp-ts-std#60]
It's a bit annoying to import from both `fp-ts/Array` and `fp-ts-std/Array`, if the latter could re-export everything from the former that'd be very ergonomic. Not sure if this is actually desirable though... I'll leave this issue open to gather feedback.

**Comment by kalda341** [comment]
On the surface it sounds like a great idea (and definitely something I've thought in the past), but there may be issues I haven't thought of.

**Comment by samhh** [comment]
I'm going to close this.

At @unsplash we have a "facade" directory in which library/type modules are re-exported. This is more flexible than anything we can do within the scope of this library as it also allows you to define your own utilities. For example:

```ts
export * from 'fp-ts/number'
export * from 'fp-ts-std/Number'

export const magic = 42
```
