### ISSUE TITLE
Support ES modules

### ISSUE THREAD

**Issue by samhh** [samhh/fp-ts-std#7]
Not considered it at all thus far, very likely needs attention.

**Comment by waynevanson** [comment]
As long is all functions,  users can tree shake their own stuff :)

**Comment by OliverJAsh** [comment]
fp-ts tree shakes extremely well, and I think we could use a similar setup:

- `pkg.main` points to CommonJS
- `pkg.module` points to ES Modules (tree shakeable)

There's a few nuances around setting this up, e.g. using `import-path-rewrite`, but it would be easy to copy the setup from somewhere like io-ts or one of the other packages in the fp-ts ecosystem such as fp-ts-rxjs—they all use this setup.

https://github.com/gcanti/io-ts/blob/920b21ea32e82b328cd14ff4b28da72ae60db505/package.json#L18

**Comment by samhh** [comment]
I've created a branch, `esm`, with a [commit](https://github.com/samhh/fp-ts-std/commit/f241ea5d867659f00a9ea79e6e73e9182ae5cda3) that attempts to support ESM. I'm hoping the conditional npm manifest bits have done the trick.

I've not got a project I can easily test this on right now; Webpack wouldn't import with ESM (given imports not ending in `.js`), and Rollup wouldn't import CJS without further configuration for comparison.

If anyone wants to investigate locally one option is to clone the repo, checkout the branch, run `yarn link`, and then likewise `yarn link fp-ts-std` where you want to try it.

Something else to look at after this is working is `/*#__PURE__*/` annotations.

**Comment by waynevanson** [comment]
There's some fp-ts-scripts somewhere that generate the module's so they're esm and cjs friendly.

**Comment by samhh** [comment]
TS 4.5 still doesn't support conditional exports properly. [This](https://github.com/microsoft/TypeScript/issues/33079#issuecomment-860721524) attempted workaround - which looks similar to what RxJS does - caused some bizarre errors in a test project:

```
node_modules/fp-ts/lib/TaskThese.d.ts:75:44 - error TS2344: Type '"TaskThese"' does not satisfy the constraint 'keyof URItoKind2<any, any>'.

75 export declare const fromThese: FromThese2<URI>['fromThese']
                                              ~~~

node_modules/fp-ts/lib/TaskThese.d.ts:278:44 - error TS2344: Type '"TaskThese"' does not satisfy the constraint 'keyof URItoKind2<any, any>'.

278 export declare const FromThese: FromThese2<URI>
                                               ~~~
```

Let's implement it similarly to fp-ts until TS support for this improves.

**Comment by samhh** [comment]
Same problem with a [more direct approach](https://github.com/samhh/fp-ts-std/commit/9660385840b111c18a31e66594ce8478e218958e). :exploding_head:

**Comment by samhh** [comment]
This might be an issue with local Yarn linking. :rage:
