### ISSUE TITLE
ReaderIO asksIO

### ISSUE THREAD

**Issue by samhh** [samhh/fp-ts-std#82]
And others.

**Comment by stefanoCrmg** [comment]
What would be the use case for `asksIO`? 🤔 Just a stricter `R.asks`? 
e.g `export const asksIO: <R1, A>(f: (r1: R1) => IO.IO<A>) => RIO.ReaderIO<R1, A> = R.asks`

Would you mind expanding on the `and others`? 😝 Are you looking for `asksTaskEither` on RTE and similar operations?

**Comment by samhh** [comment]
It's been a while! Let's think.

I think if you're in a stacked monadic context like `ReaderIO` it's ideal if everything you need exists in that module/namespace. Additionally I think `R.asks` only works there by relying on an implementation detail in how fp-ts represents stacked monads.

I suspect that's indeed what I meant by "and others". The same would apply to every `ReaderT`-based type.

**Comment by samhh** [comment]
Blocked awaiting fp-ts 2.13.

**Comment by samhh** [comment]
https://github.com/samhh/fp-ts-std/commit/922f0bad63524adecb0fbcb0b128cb9bd1772ff1..https://github.com/samhh/fp-ts-std/commit/355d472c36e359d3b51221ae1ae61956372bcb77
